### ISSUE TITLE
Saral App Non-Black Pen,Pencil filled OMR Detection

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#15]
### Discussed in https://github.com/orgs/Sunbird-Saral/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **karsood** August 19, 2022</sup>
Observation: With students filling out the OMR form, bringing the control on choice of pen will require extreme admin control.

Desire: Enhanced accuracy for blue ink + other colours</div>

To Support Non-Black Pen,Pencil filled OMR Detection as experimental feature that can be enabled with flag in layout roi json

**Comment by navin9584** [comment]
ExperimentalOMR feature will work only if experimentalOMRDetection is true in layout roi json

**Comment by apurvabisht97** [comment]
pencil omr detection is possible now by adding experimentalOMRDetection  field in roi . when its true we can detect pencil detection of omr .
