### ISSUE TITLE
Reduce Saral App bundle/APK size

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#16]
Reduce Saral App bundle/APK size

**Options to consider:**
gradle.properties
android.enableR8=true

**build.gradle**
shrinkResources enableProguardInReleaseBuilds
zipAlignEnabled enableProguardInReleaseBuilds
useProguard enableProguardInReleaseBuilds
// resConfigs "en"
minifyEnabled enableProguardInReleaseBuilds
proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"

**Snapshot of current APK size:**
![image](https://user-images.githubusercontent.com/89640648/186391115-8b402050-2fe9-4d60-9832-ffae278be969.png)

**Comment by navin9584** [comment]
Reduce Saral App bundle/APK size

**option to consider**
**gradle.properties**
android.enableR8=true

**build.gradle**
 minifyEnabled true
  shrinkResources true
  proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"

**progaurd-rules.pro**
-keep class com.saralapp.MainActivity
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep class * extends com.bumptech.glide.module.AppGlideModule {
 <init>(...);
}
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
-keep class com.bumptech.glide.load.data.ParcelFileDescriptorRewinder$InternalRewinder {
  *** rewind();
}

**Before enable setting**
![Screenshot (97)](https://user-images.githubusercontent.com/91952702/189890040-b8d39fc3-3ffd-4f41-bc21-6a4c64f9f568.png)

**After enable setting**
![Screenshot (99)](https://user-images.githubusercontent.com/91952702/189891201-cdf77f1b-47c2-46cf-be13-0543e121002e.png)
