### ISSUE TITLE
Saral offline mode support

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#17]
To support Saral App in areas where internet coverage is limited, offline mode support is to be added:

- Backend API call responses to be stored in local storage if the offline mode is enabled in /login API configuration.
- After first call the data will be cached in local storage and avoids making subsequent API calls to the backend.
- User to have provision to clear local storage and get the latest response from backend APIs
- saveMarks,/login API needs internet connectivity to the backend APIs even in offline mode.

**Comment by apurvabisht97** [comment]
offline mode is a mode when internet facility is not available then also the app should work . we can go to the app and do our task  .
