### ISSUE TITLE
Anganawadi Beneficiary Details Layout Design,ROI Generation and Verification

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#19]
Anganawadi Benificiary Details Layout Design,ROI Generation and Verification

**Comment by apurvabisht97** [comment]
beneficary detials layout roi generation is complete below is the link
https://github.com/Sunbird-Saral/Project-Saral/blob/v1-develop/v1.0/backend/data/layout/beneficiary_details.json
