### ISSUE TITLE
Anganawadi beneficiary growth Monitoring Layout Design,ROI Generation,Testing

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#20]
Anganawadi beneficiary growth Monitoring Layout Design,ROI Generation,Testing

**Comment by apurvabisht97** [comment]
roi generation for layout is complete
https://github.com/Sunbird-Saral/Project-Saral/blob/v1-develop/v1.0/backend/data/layout/benificiary-growth-monitoring-details(Age%20in%20months%200%20to%206).json
