### ISSUE TITLE
Selection of Set

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#24]
### Discussed in https://github.com/orgs/Sunbird-Saral/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **karsood** September 22, 2022</sup>
As of today, there are three selections that are made after logging in: Class, Section, and Subject.

With some states going for repeated examination using different sets (set A, set B, set C, set D), can we have sets come up as a selection after the subject is selected?

Benefit: This will help reduce selection error by the teacher.

If there are no sets for a round of examination in a state, the default entry can be A, as we have it for section selection.</div>

**Comment by apurvabisht97** [comment]
selection of set according to the class/sec and subject is now available in the app.
