### ISSUE TITLE
Switch option between the minimal and regular mode in Saral App

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#27]
Switch option between the minimal and regular mode in Saral App

**Comment by apurvabisht97** [comment]
we have added one more menu in profile menu from where we can switch between the modes of app . user have a choice in which mode they want to use the app.
Mode will be visible according to the backend flag . if isMinimalMode flag in login API is true then first screen will be of minimal mode and second will be regular mode and Vice versa.
