### ISSUE TITLE
Login API Auth token should have actual school or orgId as userId instead of mongo internal id 

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#30]
Login API Auth token should have actual school or orgId as userId instead of mongo internal id .

**Comment by dileep-gadiraju** [comment]
login API has now schoolId instead of mongodId . Auth token is updated with school id in backend .

**Comment by apurvabisht97** [comment]
auth token now have schoolid instead of mongo _id .
