### ISSUE TITLE
App force update when a new version of app is available in playstore with backend config

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#33]
App force updates when a new version of the app is available in the play store.

- An option in the backend configuration with apkVersionId, and apkVersion details.
- If Backend configuration is done to force an update, version details also need to be passed.

**Comment by dileep-gadiraju** [comment]
https://stackoverflow.com/questions/19244305/force-update-of-an-android-app-when-a-new-version-is-available

**Comment by arman-tdev** [comment]
Dev testing in progress...

1) In backend we have configured a flag which name is "isAppForceUpdateEnabled"
2) If isAppForceUpdateEnabled flag is true then app force update feature will be triggered
3) If playstore's app has a new version then in app there would an alert populate which show user an alert message to force app update.
4) If there is any error occurred while populating alert message of app force update we are supporting to share error log with dev team.

**Comment by dileep-gadiraju** [comment]
Hi @arman-tdev and team,

For testing the force update feature, refer to the below links:

https://stackoverflow.com/questions/56087064/how-can-i-test-in-app-updates-in-android
https://developer.android.com/reference/com/google/android/play/core/appupdate/testing/FakeAppUpdateManager

**Comment by dileep-gadiraju** [comment]
Hi @arman-tdev ,

multiple users on the same device- If marks Info is already saved in the device make sure that data don't lose marks data.

**Comment by dileep-gadiraju** [comment]
Hi @arman-tdev ,

Also explore if an app is already open and if there is a version update in the play store, an event to be triggered on all key clicks on the app (Save All Marks, Scan, etc).
