### ISSUE TITLE
Saral App global Cache clear functionality

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#36]
Saral App global Cache clear functionality:

1. /brand/default API response is currently cached as a global cache in offlineMode. When the user clears the All User Cache, this default branding should be fetched from the backend API for the first time.

**Comment by arman-tdev** [comment]
1. working on to clear branding cache from user cache

**Comment by apurvabisht97** [comment]
this pr is merge with v1-develop .
Now when we have one school stored in cache and we do clear
