### ISSUE TITLE
Locking the exams for scanning(recommencation from u.p implementation)

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#41]
Locking the exams for scanning(recommendation from u.p implementation)

- Reference backend implementation of locking functionality at the state/district/school level
- App integration with locking functionality
- Documentation

Tentative Dev Completion Date: 28th Nov 2022

**Comment by apurvabisht97** [comment]
https://github.com/Sunbird-Saral/Project-Saral/pull/307

**Comment by navin9584** [comment]
PR:--https://github.com/Sunbird-Saral/Project-Saral/pull/307 
By this PR now able to Locking the exams for scanning verified all the test cases it is working
