### ISSUE TITLE
Student Absent/Present marking to be done offline and sync with backend during final marks upload using /saveMarks API 

### ISSUE THREAD

**Issue by dileep-gadiraju** [Sunbird-Saral/Community#47]
Student Absent/Present marking is to be done offline and synced with the backend during final marks upload using /saveMarks API 

- This is to optimize the overall workflow and avoid intermediate /saveMarks calls during absent/present marking on the student list page.

Tentative Dev Completion Date: 28th Nov 2022

**Comment by apurvabisht97** [comment]
**PR LINK **:- https://github.com/Sunbird-Saral/Project-Saral/pull/308

**Earlier flow:-**
user will be able to mark any student as absent/present on student list page and then it is saved directly in database via save marks API. In earlier flow there were two calls  happening for save Marks API during student list page and  final marks upload.

**PR TEST CASES**

1. user will be able to mark any student  as absent or present either network is enable or not but it is saved on database during final marks uploading .
